name: Deploy to ghcr.io

on:
  push:
    branches:
      - rebuild-base-img

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: muncomputersciencesociety
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          tags: ghcr.io/muncomputersciencesociety/executive-docs-base-img:latest
